data:
    dataset: "_128"
    category: "imagenet"

model:
    freq: 0
    attention_resolutions: '32,16,8'
    class_cond: False
    diffusion_steps: 1000
    rescale_timesteps: True
    timestep_respacing: '1000'  # Modify this value to decrease the number of timesteps.
    image_size: 128
    learn_sigma: True
    noise_schedule: 'linear'
    num_channels: 128
    num_head_channels: 64  # previously is 64
    num_res_blocks: 2
    resblock_updown: True
    use_fp16: True
    use_scale_shift_norm: True

sampling:
    batch_size: 8
    last_only: True